import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial import Voronoi, voronoi_plot_2d
from shapely.geometry import Polygon, Point
import requests
import os

def get_sf_trees():
    """Fetch a small subset of tree data."""
    api_endpoint = "https://data.sfgov.org/resource/tkzw-k3nq.json"
    api_params = {"$limit": 500, "$offset": 1000} # Small subset for Voronoi
    response = requests.get(api_endpoint, params=api_params)
    response.raise_for_status()
    df = pd.DataFrame(response.json())
    df = df.astype({"latitude": "float64", "longitude": "float64"})
    return df.dropna(subset=['latitude', 'longitude'])

def main():
    print("Fetching points for generative map...")
    df = get_sf_trees()
    points = df[['longitude', 'latitude']].values
    
    # Filter points to a tight box in SF (e.g. Mission District area)
    mask = (points[:, 0] > -122.43) & (points[:, 0] < -122.40) & \
           (points[:, 1] > 37.74) & (points[:, 1] < 37.77)
    points = points[mask]
    
    if len(points) < 10:
        print("Not enough points in the selected area. Using all.")
        points = df[['longitude', 'latitude']].values
    
    print(f"Generating Voronoi with {len(points)} points...")
    vor = Voronoi(points)
    
    print("Plotting...")
    fig, ax = plt.subplots(figsize=(12, 12))
    fig.patch.set_facecolor('#0a0a1a') # Deep space blue
    ax.set_facecolor('#0a0a1a')
    
    # Create colors
    colors = ['#ff00ff', '#00ffff', '#ffff00', '#ff0000', '#00ff00', '#0000ff']
    
    # Plot Voronoi regions
    for i, region_idx in enumerate(vor.point_region):
        region = vor.regions[region_idx]
        if -1 not in region and len(region) > 0:
            polygon = [vor.vertices[i] for i in region]
            ax.fill(*zip(*polygon), color=np.random.choice(colors), alpha=0.4, edgecolor='white', linewidth=0.5)
    
    # Plot the original points as "stars"
    ax.scatter(points[:, 0], points[:, 1], s=2, color='white', alpha=0.8)
    
    ax.set_axis_off()
    ax.set_title('Neural Hallucination: SF Grid #09', color='#00ffff', fontsize=24, pad=20, fontname='monospace')
    
    ax.text(0.5, 0.02, "GENERATED BY GEMINI-CLI // SEED: 30DAYMAPCHALLENGE", 
            transform=ax.transAxes, ha='center', color='#ff00ff', fontsize=10, fontname='monospace')
    
    output_path = os.path.join('2024', 'day_9', 'visualization', 'sf_ai_hallucination.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='#0a0a1a')
    print(f"Saved to {output_path}")

if __name__ == "__main__":
    main()
